### ISSUE TITLE
Question: kleur instances

### ISSUE THREAD

**Issue by icebob** [lukeed/kleur#48] opened 2021-06-13 14:57 UTC
Hi Luke,

is there any way to create an instance of kleur?
In Moleculer loggers I have an issue with enable/disable coloring because all loggers use the same imported kleur instance.

Use case: There are two loggers, first is a console logger which enables colors and prints the messages with colors, the second is a file logger which disabled the colors, but both of them use the same kleur so the colorizing works weird.

Do you have any idea, how I can solve it?

Thanks in advance!

**Comment by lukeed** [comment] 2021-06-16 05:38
Hey :)

There isn't a way – that I know of at least. Kleur is meant to be used a singleton, and (afaik) the module format(s) make it so that your application shares the same code (ergo the same context). This is why something like `clone = Object.assign({}, kleur)` wouldnt work.

If you _plan_ on having two instances, and one always has colorization disabled, then I would just do something like this, which would work with `kleur` and `kleur/colors`:

```js
const kleur = require('kleur');

function print(txt) {
  return txt === void 0 ? this : ''+txt;
}

/**
 * @returns {typeof kleur}
 */
function shell() {
  var $={}, k, x, y;
  var log = print.bind($);
  for (k in kleur) {
    x = kleur[k];
    y = typeof x;
    $[k] = (
      y === 'function' ? log
      : y === 'object' ? { ...x }
      : x
    );
  }
  return $;
}

const clone = shell();
console.log(clone);
//=> mimics `kleur` interface

console.log(
  JSON.stringify(clone.red().blue().bgWhite('hello'))
);
//=> "hello"
```

I'm going to close this as a "works as intended" – but please feel free to follow up if you have any other questions!

**Closed by lukeed** 2021-06-16 05:38 UTC
